apiVersion: v1
data:
  images.json: |-
    [
      "https://i.imgflip.com/7jqevq.jpg",
      "https://i.imgflip.com/7jqekl.jpg",
      "https://i.imgflip.com/7jmwjs.jpg",
      "https://media.istockphoto.com/id/508030340/photo/sunny-cat.jpg?s=612x612&w=0&k=20&c=qkz-Mf32sbJnefRxpB7Fwpcxbp1fozYtJxbQoKvSeGM="
    ]
kind: ConfigMap
metadata:
  name: images-json
  labels:
    app: random-meme
